package it.develhope.fileUploadDownload.entities;


import javax.persistence.*;

/**
 * @author Drumstyle92
 * class used in the user management system where users
 * have a profile that includes their name,
 * email address, and a profile picture
 */
@Entity
@Table(indexes = {

        @Index(unique = true, name = "email_idx", columnList = "email")

 } )
public class User {

    /**
     * variable id is a Long automatically generated by a sequence
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;

    /**
     * user name variable
     */
    @Column(name = "first_name")
    private String firstName;

    /**
     * user last name variable
     */
    @Column(name = "last_name" )
    private String lastName;

    /**
     * unique key user email variable
     */
    @Column(unique = true)
    private String email;

    /**
     * user image variable
     */
    @Column(name = "profile_picture")
    private String profilePicture;

    /**
     * default constructor of the class
     */
    public User(){}

    /**
     * @param id             the id
     * @param firstName      the first name
     * @param lastName       the last name
     * @param email          the email
     * @param profilePicture the profile picture
     * Parameterized constructor of the class
     */
    public User(Long id, String firstName, String lastName, String email, String profilePicture) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.profilePicture = profilePicture;
    }

    /**
     * @return the id
     * Method for encapsulation
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the id
     * Method for encapsulation
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return the first name
     * Method for encapsulation
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * @param firstName the first name
     * Method for encapsulation
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * @return the last name
     * Method for encapsulation
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * @param lastName the last name
     * Method for encapsulation
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * @return the email
     * Method for encapsulation
     */
    public String getEmail() {
        return email;
    }

    /**
     * @param email the email
     * Method for encapsulation
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * @return the profile picture
     * Method for encapsulation
     */
    public String getProfilePicture() {
        return profilePicture;
    }

    /**
     * @param profilePicture the profile picture
     * Method for encapsulation
     */
    public void setProfilePicture(String profilePicture) {
        this.profilePicture = profilePicture;
    }

}
