spring:
  datasource:
    url: jdbc:h2:mem:BaseDb
    username: test
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

fileRepositoryFolder: C:\\Users\\dino_\\Desktop\\FileRepository